services:
  musicbot:
    container_name: musicbot
    image: ghcr.io/snaacky/musicbot:latest
    restart: unless-stopped
    volumes:
      - ./config:/config
    environment:
      - DISCORD_TOKEN=xxxxxxxxxxxxxxxxxxxx
      - CLIENT_ID=xxxxxxxxxxxxxxxxxxxx
      - GUILD_ID=xxxxxxxxxxxxxxxxxxxx,yyyyyyyyyyyyyyyyyyyy
      - SPOTIFY_CLIENT_ID=xxxxxxxxxxxxxxxxxxxx
      - SPOTIFY_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxx
      - STATUS=/play
      - EMBED_COLOR=#14c4ff
      - COOKIES_FILE=/config/cookies.txt
